-- DDL for table br_departments                                              
CREATE SET TABLE Payroll_DB.br_departments ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      department_number BYTEINT NOT NULL,      acronym VARCHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC,      department_name VARCHAR(75) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,      budget_amount DECIMAL(12,2),      manager_employee_number INTEGER, FOREIGN KEY ( manager_employee_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_payroll ( employee_number ))UNIQUE PRIMARY INDEX ( department_number );

-- DDL for table br_divisions                                                
CREATE SET TABLE Payroll_DB.br_divisions ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      department_number BYTEINT NOT NULL,      division_number INTEGER NOT NULL,      division_name VARCHAR(75) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL, FOREIGN KEY ( department_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_departments ( department_number ))UNIQUE PRIMARY INDEX ( division_number );

-- DDL for table br_jobs                                                     
CREATE SET TABLE Payroll_DB.br_jobs ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      job_code INTEGER NOT NULL,      pay_grade SMALLINT,      legacy_flag BYTEINT NOT NULL,      job_title VARCHAR(80) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL)UNIQUE PRIMARY INDEX ( job_code );

-- DDL for table br_payroll                                                  
CREATE SET TABLE Payroll_DB.br_payroll ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      employee_number INTEGER NOT NULL,      last_name VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,      first_name VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,      middle_initial CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC,      name_suffix VARCHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,      birthdate DATE FORMAT 'yyyy-mm-dd' NOT NULL,      department_number BYTEINT NOT NULL,      division_number INTEGER NOT NULL,      job_code INTEGER,      pay_grade SMALLINT,      pay_step BYTEINT,      gender CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC NOT NULL,      race CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC NOT NULL,      hire_date DATE FORMAT 'YYYY-MM-DD' NOT NULL,      hire_end_date DATE FORMAT 'YYYY-MM-DD',      years_service BYTEINT NOT NULL,      scheduled_hours DECIMAL(4,1) NOT NULL,      longevity_percentage DECIMAL(2,2) NOT NULL,      base_hourly_rate DECIMAL(5,2) NOT NULL,      total_hourly_rate DECIMAL(5,2) NOT NULL,      overtime_hourly_rate DECIMAL(5,2) NOT NULL,      annual_salary DECIMAL(8,2) NOT NULL,      status BYTEINT NOT NULL, FOREIGN KEY ( department_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_departments ( department_number ),FOREIGN KEY ( division_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_divisions ( division_number ),FOREIGN KEY ( job_code ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_jobs ( job_code ),FOREIGN KEY ( pay_grade ,pay_step ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_pay_plan ( pay_grade ,pay_step ))UNIQUE PRIMARY INDEX ( employee_number );

-- DDL for table br_pay_plan                                                 
CREATE SET TABLE Payroll_DB.br_pay_plan ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      pay_grade SMALLINT NOT NULL,      pay_step BYTEINT NOT NULL,      annual_salary DECIMAL(9,2) NOT NULL)PRIMARY INDEX ( pay_grade );

-- DDL for table br_salary_hist                                              
CREATE SET TABLE Payroll_DB.br_salary_hist ,FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO,     MAP = TD_MAP1     (      employee_number INTEGER NOT NULL,      sal_year SMALLINT NOT NULL,      last_name VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,      first_name VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,      middle_initial CHAR(1) CHARACTER SET LATIN UPPERCASE NOT CASESPECIFIC,      name_suffix VARCHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,      department_number BYTEINT NOT NULL,      division_number INTEGER NOT NULL,      job_code INTEGER NOT NULL,      hire_date DATE FORMAT 'YYYY-MM-DD' NOT NULL,      employment_end_date DATE FORMAT 'YYYY-MM-DD',      scheduled_hours SMALLINT NOT NULL,      longevity_percentage DECIMAL(2,2) NOT NULL,      base_hourly_rate DECIMAL(5,2) NOT NULL,      total_hourly_rate DECIMAL(5,2) NOT NULL,      overtime_hourly_rate DECIMAL(5,2) NOT NULL,      total_pay DECIMAL(9,2) NOT NULL,      base_pay DECIMAL(9,2) NOT NULL,      overtime_pay DECIMAL(9,2) NOT NULL,      overtime_hours DECIMAL(6,2) NOT NULL,      status BYTEINT NOT NULL, FOREIGN KEY ( department_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_departments ( department_number ),FOREIGN KEY ( division_number ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_divisions ( division_number ),FOREIGN KEY ( job_code ) REFERENCES WITH NO CHECK OPTION Payroll_DB.br_jobs ( job_code ))PRIMARY INDEX ( employee_number );

